### ISSUE TITLE
Display shifted

### ISSUE THREAD

**Issue by Shogun1978** [masto/NSPanel-Demo-Files#1]
Maybe it is not related to the NSPanel files here, but you might know a solution. I use the EU version of the display. In the Nextion editor I chose "270°" as orientation. The UI is shown correctly, but moved slidely to the right side (buttons below the display). Also the buttons are not always responding at the border of the buttons. Seems like everything is shifted. Am I doing something wrong?

**Comment by masto** [comment]
You're not doing something wrong, but there is a trick to get it working that was only discovered today. You can put this command:

```
lcd_dev fffb 0002 0000 0020
```

into Program.s (tab at the top of the editor window), and it should fix the problem.

Video coming on this soon...

**Comment by Shogun1978** [comment]
Nope, didn't work out. The display is still shifted. The touch area is correct, but the displayed items are shifted to the right of the display.

**Comment by masto** [comment]
I don’t have the EU model, but from what I understand the display is partially covered up by the bezel; the only solution there is to not use that part of the screen.

**Comment by Shogun1978** [comment]
I see. I will play around a little bit. I have the feeling it's really covered or some kind of stretched... I will take a look when I unmount it next time.

**Comment by Shogun1978** [comment]
Ok, update: I checked the data sheet of the display itself: https://nextion.tech/datasheets/nx4832f035/
Here you can find: Visual Area (V.A.) | 73.44mm(L)×48.96mm(W)
I took a ruler and found out, that the height from 48.96 mm is correct, the width is just 69 mm - so we miss approx. 4 mm. Testing this out, it means that 25-26 px in fact are "missing" so covered behind the frame. So if you design a layout, calculate 453 or 454x320 px. Then it will work out. I tested with 454 which worked out pretty well for me. Maybe you can share this information in your next tutorial as I know that a lot of EU versions are out here (at least here in Germany I know a few people ;-) )
