### ISSUE TITLE
Unable to flash

### ISSUE THREAD

**Issue by napalmz** [masto/NSPanel-Demo-Files#2]
I found your guide and brought a NSPanel EU model.
Connected 3v3, TX, RX and GND of the FDI Flasher to the corresponding holes in the board.
Also connected IO0 to GND (on FDI) to activate flashing mode (i suppose).
![IMG_3260](https://user-images.githubusercontent.com/5747804/149330333-980de423-e8c9-4800-825b-a1d299d10cf5.jpg)

Serial port pops out in EspHome Flasher but then i try to flash:
```
Using '/dev/cu.usbserial-A50285BI' as serial port.
Connecting......................................
Unexpected error: ESP Chip Auto-Detection failed: Failed to connect to Espressif device: No serial data received.
For troubleshooting steps visit: https://github.com/espressif/esptool#troubleshooting
```
FDI board works because i've used it yesterday to flash an ESP8266 correctly.
Is a connection problem on the board? is a flash problem with the IO0 pin?
What can i try?

Thank you.

**Comment by Shogun1978** [comment]
That happened to me also, sometimes it helps to check the connections to the NSpanel board itself (if you didn't solder it) and additionally just unplug and re-plug the USB. Seems like something hangs up. I guess (as I ran into the same problem) that the USB connector could not contact the ESP on the NSPanel. I also own the EU version, so I hope it helps you. On your picture all looks pretty "secure", but if not soldered, the risk of a not connected pin is still there and the error message seems to point at this issue.

**Comment by napalmz** [comment]
You successfully flashed it?

**Comment by Shogun1978** [comment]
Yes, worked after checking the connections (if all is disconnected), maybe you hold the not soldered pins not straight up to get contact to the solder points on the PCB. I running two NSPanels with customized UI after watching the video from Christopher.

**Comment by napalmz** [comment]
Is it what i do, pushed with my fingers to make contact... but it's not working.
I don't want to solder it.

UPDATE:
i just swapped RX/TX to get it invertd (RX to TX and viceversa) and it works!

Thank you

**Comment by Shogun1978** [comment]
UPDATE: Ok, too late - that came up my mind also :-) Happy flashing! :-)

Hmm... strange. For me, it worked easily... and it looks correct, what you did. Be sure that TX from the USB goes to RX from the PCB and vice versa. IO0 to GND to get it to flash mode... you might try to use a pin bar, stick the cables on the pins and hold it slightly inclined:
![20220113_142414](https://user-images.githubusercontent.com/21989682/149338590-2843553e-078e-4c3f-a03d-bafd449a9df7.jpg)
