### ISSUE TITLE
Issue with the NS panel coding

### ISSUE THREAD

**Issue by bilaljavaid123** [masto/NSPanel-Demo-Files#6]
Hello, I wanna help I have NS panel integrated with home assistant I have designed a HMI in nextion and upload the TFT in home assistant so I have two pages page id= 0 and page id=1 so in the yaml coding I just write these lines:
  - platform: nextion
    name: $device_name Touch me
    page_id: 0
    component_id: 0
    
  - platform: nextion
    name: $device_name Light
    page_id: 1
    component_id: 1

so in devices and services in home assistant everything on page 0 is working very fine but when I go to page 1 everything on page 1 like button is not working I don't know why everything on page 1 is not working if there is any coding issue?
like I clicked the light button on page 1 but my home assistant light doesn't came ON.

**Comment by masto** [comment]
This is better asked on a forum.
