### ISSUE TITLE
Wireless Compiling

### ISSUE THREAD

**Issue by DavidGabi27** [masto/NSPanel-Demo-Files#9]
I followed and compiled correctly, and it works perfectly, but I added the nspanel-demo.tft part, the device comes online and I want to compile it again, but I get this error.
![Screenshot 2024-03-11 at 16 55 08](https://github.com/masto/NSPanel-Demo-Files/assets/57777250/627242bd-42ba-4b66-b515-f8b5ee0a710b)

**Comment by masto** [comment]
I'm not able to provide end-user support for ESPHome.

**Comment by DavidGabi27** [comment]
I used the code from Git and the first time it compiled perfectly. In order to finish the nspanel-demo.tft step in the YouTube video, I have to compile again, but I can't compile unless I take out the : 
"external_components:
  - source: github://pr#2956
    components: [nextion]
    refresh: 1h"
